create table if not exists public.availability (
  id bigint generated by default as identity primary key,
  available_on date not null,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  created_at timestamptz not null default now(),
  constraint availability_date_name_unique unique (available_on, name)
);

alter table public.availability enable row level security;

grant select, insert on table public.availability to anon, authenticated;
grant usage, select on sequence public.availability_id_seq to anon, authenticated;
revoke update, delete on table public.availability from anon, authenticated;

drop policy if exists "Anyone can view availability" on public.availability;
drop policy if exists "Anyone can add availability" on public.availability;

create policy "Anyone can view availability"
on public.availability
for select
to anon, authenticated
using (true);

create policy "Anyone can add availability"
on public.availability
for insert
to anon, authenticated
with check (char_length(btrim(name)) between 1 and 80);
